### PR TITLE
Adding appId

### PR DESCRIPTION
**Pull request by r2o3k**

### CODE REVIEW

**Comment by Jyyjy** [comment]
I don't think this field is meaningfully different than toolName. Other than requiring the user to specify it. If there is a difference, can we make that clear in the read me (and fix tests)? And if not, should this PR be to make toolname required?

**Comment by EandrewJones** [comment]
Besides the fact I hate having a field entitled `toolName`---which screams this is a "descriptive, non-unique value"---be used as a unique id, it can work in theory. If I was a dictator, I'd say we migrate to appId but that would introduce breaking changes.

@r2o3k Can you simply make toolName and toolVersion mandatory fields like you have here with appId?

@Jyyjy I believe the broken tests on Node v20.x are unrelated to this ticket. We shouldn't couple them.

**Comment by EandrewJones** [comment]
Closing since this is now covered by #411.

**Comment by EandrewJones** [comment]
Closing since this is covered by #411

**Pull request closed without merging**
