### PR TITLE
Add Commitizen feature to simplify commits for #477

### PR DESCRIPTION
**Pull request by Suvendu-UI**
Added the commitizen and resolving all the previous commits, done all tests

### CODE REVIEW

**Comment by Suvendu-UI** [comment]
hey @EandrewJones  now no ci errors plus all the changes done , with no commits

**Comment by rc10house** [comment]
> hey @EandrewJones now no ci errors plus all the changes done , with no commits

@Suvendu-UI Evan and Jason will be back in office on Monday. They should be able to merge this PR then.

**Comment by EandrewJones** [comment]
> hey @EandrewJones now no ci errors plus all the changes done , with no commits

Looks beautiful -- merged. Thanks and congrats on your first commit :confetti_ball:

**Comment by Suvendu-UI** [comment]
Thank you @EandrewJones , and by the way i am GSOC aspirant for next year

**Comment by EandrewJones** [comment]
That's a great goal. We intend to get some regular virtual meetings for
Flagon on the calendar soon and would love to have you attend.


Best

Evan Jones
Website: www.ea-jones.com

**Pull request merged**
